### ISSUE TITLE
[question] Intent corpus

### ISSUE THREAD

**Issue by palmerabollo** [mlehman/nlp-intent-toolkit#6]
Hi Matt. Do you know any public corpus of sentences and intents? It would be great to compare opennlp with other services. I think that you don't have enough [examples](https://github.com/mlehman/nlp-intent-toolkit/tree/master/example/weather/train) but I haven't found anything better/bigger yet.

**Comment by mlehman** [comment]
I have not found any, but if you find some, please share a link here!
