### ISSUE TITLE
Project has no license.

### ISSUE THREAD

**Issue by stevecooperorg** [mlehman/nlp-intent-toolkit#7]
Hi - this project looks really interesting and I'd like to try building something based on it, but there's no licensing info in the project -- could you add a license file to the project, or a note in the README, to make clear the terms of use? Thanks!

**Comment by mlehman** [comment]
I've added a license that should be as permissive as possible. Since its intended as an example how to do intent recognition with OpenNLP, feel free to use any of it in your own project.

**Comment by stevecooperorg** [comment]
Thanks - that's perfect! Today we do both kinds of programming - coping _and_ pasting! :)
